# Generated by Django 2.2.7 on 2019-11-08 00:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
