# Generated by Django 2.2.7 on 2019-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191114_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.Profile'),
        ),
    ]
